### ISSUE TITLE
代码已经失效了，应该是页面小改版了，登陆不上去了

### ISSUE THREAD

**Issue by shelson-woo** [CaoZ/XueCheBu-Crack#2]

**Comment by CaoZ** [comment]
嗯, 几年前做的东西了...

**Comment by shelson-woo** [comment]
改动的地方不多。把登陆网址改一下，把密码改成md5加密，其他地方get使用cookie 就行了。

**Comment by Zack-Bee** [comment]
> 改动的地方不多。把登陆网址改一下，把密码改成md5加密，其他地方get使用cookie 就行了。

@shelson-woo 你好，请问有修改后的代码么，看你 fork 的仓库里没做更改

**Comment by shelson-woo** [comment]
> > 改动的地方不多。把登陆网址改一下，把密码改成md5加密，其他地方get使用cookie 就行了。
> 
> @shelson-woo 你好，请问有修改后的代码么，看你 fork 的仓库里没做更改
我没把改的上传，着急用么？ 周末改一下

**Comment by shelson-woo** [comment]
@Zack-Bee 我没把改的上传，着急用么？ 周末改一下

**Comment by Lotus-95** [comment]
我 fork 了代码，更新了登录接口，现在可以正常刷课了：https://github.com/Lotus-95/XueCheBu-Crack
